version: '3.9'

services:
  web:
    container_name: iga-ch-dev
    build:
      args:
        - UID=1000 #dev user uuid
    restart: always
    ports:
    - "1312:80"
    volumes:
    - ./:/var/www/html:z