version: '3.9'

services:
  web:
    container_name: managed-site-template
    build:
      args:
        - UID=1000 #dev user uuid
    restart: always
    ports:
    - "1312:80"
    volumes:
    - ./:/var/www/html:z
  mailhog:
     container_name: mailhog
     image: mailhog/mailhog:latest
     restart: always
     hostname: mailhog
     ports:
       - "1025:1025"
       - "1325:8025"